/**
 * Tests for the test-file emitter (src/emit/generate.ts).
 *
 * Covers:
 * - Deterministic header/file shape
 * - All six import transformation forms
 * - Line invariant (1:1 body correspondence)
 * - Different example kinds (assertion, throws, pending, no-run, ignored)
 * - Group merging
 * - Nested document paths
 * - Generated file execution
 */

import { expect, test } from "bun:test";
import {
  type Document,
  type DocumentationSet,
  type Example,
  generate,
  IR_VERSION,
  TOOL_NAME,
  TOOL_VERSION,
} from "metonym";

function createDocSet(
  documents: Document[],
  examples: Example[],
  root = "/tmp/x",
): DocumentationSet {
  return {
    irVersion: IR_VERSION,
    tool: { name: TOOL_NAME, version: TOOL_VERSION },
    root,
    documents,
    examples,
    symbols: [],
    relations: [],
  };
}

function codeLines(code: string): string[] {
  return code.split("\n");
}

function getBodyLines(
  code: string,
  startLine: number,
  endLine: number,
): string[] {
  const lines = codeLines(code);
  // genCodeStartLine and genCodeEndLine are 1-indexed; convert to 0-indexed array access
  return lines.slice(startLine - 1, endLine);
}

function _assertLineInvariant(
  generatedCode: string,
  docCode: string,
  genCodeStartLine: number,
  genCodeEndLine: number,
): void {
  const genLines = getBodyLines(
    generatedCode,
    genCodeStartLine,
    genCodeEndLine,
  );
  const docLines = docCode.split("\n");

  expect(genLines).toHaveLength(docLines.length);
  for (let i = 0; i < docLines.length; i++) {
    const genLine = genLines[i].replace(/^ {4}/, "");
    const _docLine = docLines[i];
    expect(genLine).toBeDefined();
  }
}

test("header lines are exact and deterministic", () => {
  const doc: Document = {
    id: "doc:README.md",
    file: "README.md",
    origin: "readme",
    title: "Test",
    exampleIds: ["ex:README.md:abc123"],
  };

  const ex: Example = {
    id: "ex:README.md:abc123",
    documentId: "doc:README.md",
    source: {
      file: "README.md",
      start: { line: 10, column: 1, offset: 100 },
      end: { line: 11, column: 1, offset: 150 },
    },
    fenceSource: {
      file: "README.md",
      start: { line: 9, column: 1, offset: 90 },
      end: { line: 12, column: 1, offset: 160 },
    },
    language: "ts",
    code: "expect(1).toBe(1)",
    kind: "assertion",
    title: "Example 1",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  const lines = codeLines(generated.code);
  expect(lines[0]).toBe(
    `// README.md.test.ts — generated by metonym v${TOOL_VERSION}. DO NOT EDIT.`,
  );
  expect(lines[1]).toBe("// source: README.md");
  expect(lines[2]).toBe(`import { describe, test, expect } from "bun:test";`);
  expect(lines[3]).toBe("");
  expect(lines[4]).toBe(`describe("README.md", () => {`);

  const docSet2 = createDocSet([doc], [ex]);
  const [generated2] = generate(docSet2);
  expect(generated2.code).toBe(generated.code);
});

test("all six import transformation forms", () => {
  const imports = [
    'import d from "m"',
    'import { a, b as c } from "m"',
    'import * as ns from "m"',
    'import d, { a as b } from "m"',
    'import "m"',
    'import type T from "m"',
  ];

  const expected = [
    'const { default: d } = await import("m");',
    'const { a, b: c } = await import("m");',
    'const ns = await import("m");',
    'const { default: d, a: b } = await import("m");',
    'await import("m");',
    "// metonym: type-only import elided",
  ];

  for (let i = 0; i < imports.length; i++) {
    const doc: Document = {
      id: `doc:test${i}.md`,
      file: `test${i}.md`,
      origin: "markdown",
      exampleIds: [`ex:test${i}.md:${i}`],
    };

    const ex: Example = {
      id: `ex:test${i}.md:${i}`,
      documentId: `doc:test${i}.md`,
      source: {
        file: `test${i}.md`,
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: imports[i].length },
      },
      fenceSource: {
        file: `test${i}.md`,
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: imports[i].length },
      },
      language: "ts",
      code: imports[i],
      kind: "assertion",
      title: `Import test ${i}`,
    };

    const docSet = createDocSet([doc], [ex]);
    const [generated] = generate(docSet);
    const lines = codeLines(generated.code);

    const testStartIdx = lines.findIndex((l) => l.includes("test("));
    expect(testStartIdx).toBeGreaterThanOrEqual(0);

    let bodyStart = testStartIdx + 1;
    while (bodyStart < lines.length && lines[bodyStart].trim() === "") {
      bodyStart++;
    }

    let foundTransformed = false;
    for (let j = bodyStart; j < lines.length && j < bodyStart + 10; j++) {
      const line = lines[j];
      if (
        line.includes("const") ||
        line.includes("await import") ||
        line.includes("// metonym: type-only")
      ) {
        // For type-only imports, the whole line should match
        if (expected[i].includes("//")) {
          if (line.trim().includes(expected[i])) {
            foundTransformed = true;
          }
        } else {
          // For other imports, check that the expected string is in the line
          if (line.includes(expected[i])) {
            foundTransformed = true;
          }
        }
        if (foundTransformed) break;
      }
    }
    expect(foundTransformed).toBe(true);
  }
});

test("line invariant: body lines map 1:1 to source", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:abc123"],
  };

  const bodyCode = `const x = 1;
const y = 2;
expect(x + y).toBe(3);`;

  const ex: Example = {
    id: "ex:test.md:abc123",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 8, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 9, column: 1, offset: 110 },
    },
    language: "ts",
    code: bodyCode,
    kind: "assertion",
    title: "Multi-line test",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  const entry = generated.map.entries[0];
  expect(entry).toBeDefined();
  expect(entry.genCodeStartLine).toBeLessThanOrEqual(entry.genCodeEndLine);

  const genBodyLines = getBodyLines(
    generated.code,
    entry.genCodeStartLine,
    entry.genCodeEndLine,
  );

  expect(genBodyLines).toHaveLength(3);

  const trimmed = genBodyLines.map((l) => l.replace(/^ {4}/, ""));
  const expectedLines = bodyCode.split("\n");
  for (let i = 0; i < trimmed.length; i++) {
    expect(trimmed[i]).toBe(expectedLines[i]);
  }
});

test("throws examples wrap in try/catch", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:abc123"],
  };

  const ex: Example = {
    id: "ex:test.md:abc123",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 6, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 7, column: 1, offset: 110 },
    },
    language: "ts",
    code: "throw new Error('test');",
    kind: "throws",
    title: "Throws test",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  const code = generated.code;
  expect(code).toContain("let __threw = false;");
  expect(code).toContain("try {");
  expect(code).toContain("} catch {");
  expect(code).toContain("__threw = true;");
  expect(code).toContain("expect(__threw).toBe(true);");
});

test("pending examples generate test.todo", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:abc123"],
  };

  const ex: Example = {
    id: "ex:test.md:abc123",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 6, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 7, column: 1, offset: 110 },
    },
    language: "ts",
    code: "// future API",
    kind: "pending",
    title: "Pending API",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  const code = generated.code;
  expect(code).toContain('test.todo("Pending API (test.md:5)");');
  expect(code).not.toContain("async () => {");

  const entry = generated.map.entries[0];
  expect(entry.kind).toBe("pending");
  expect(entry.genCodeStartLine).toBe(entry.genCodeEndLine);
});

test("no-run examples validate but emit no test", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:good", "ex:test.md:bad", "ex:test.md:valid"],
  };

  const goodEx: Example = {
    id: "ex:test.md:good",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 6, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 7, column: 1, offset: 110 },
    },
    language: "ts",
    code: "const x = 1;",
    kind: "no-run",
    title: "Valid no-run",
  };

  const badEx: Example = {
    id: "ex:test.md:bad",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 10, column: 1, offset: 150 },
      end: { line: 11, column: 1, offset: 200 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 9, column: 1, offset: 140 },
      end: { line: 12, column: 1, offset: 210 },
    },
    language: "ts",
    code: "const = {",
    kind: "no-run",
    title: "Invalid no-run",
  };

  const validEx: Example = {
    id: "ex:test.md:valid",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 15, column: 1, offset: 250 },
      end: { line: 16, column: 1, offset: 300 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 14, column: 1, offset: 240 },
      end: { line: 17, column: 1, offset: 310 },
    },
    language: "ts",
    code: "expect(1).toBe(1);",
    kind: "assertion",
    title: "Real test",
  };

  const docSet = createDocSet([doc], [goodEx, badEx, validEx]);
  const [generated] = generate(docSet);

  expect(generated.code).not.toContain("const x = 1;");
  expect(generated.code).not.toContain("const = {");

  expect(generated.code).toContain("expect(1).toBe(1);");

  expect(generated.diagnostics).toBeDefined();
  expect(generated.diagnostics?.length).toBeGreaterThan(0);
  expect(generated.diagnostics?.[0]).toContain(
    "no-run example failed to transpile",
  );
  expect(generated.diagnostics?.[0]).toContain("test.md:10");
});

test("group merge: multiple examples with same group", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:1", "ex:test.md:2"],
  };

  const ex1: Example = {
    id: "ex:test.md:1",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 6, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 7, column: 1, offset: 110 },
    },
    language: "ts",
    code: "const db = {};",
    kind: "assertion",
    group: "setup",
    title: "Setup - part 1",
  };

  const ex2: Example = {
    id: "ex:test.md:2",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 15, column: 1, offset: 150 },
      end: { line: 16, column: 1, offset: 200 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 14, column: 1, offset: 140 },
      end: { line: 17, column: 1, offset: 210 },
    },
    language: "ts",
    code: "expect(db).toBeDefined();",
    kind: "assertion",
    group: "setup",
    title: "Setup - part 2",
  };

  const docSet = createDocSet([doc], [ex1, ex2]);
  const [generated] = generate(docSet);

  const code = generated.code;
  expect(code).toContain('test("group:setup');
  expect(code).toContain("const db = {};");
  expect(code).toContain("expect(db).toBeDefined();");

  expect(generated.map.entries).toHaveLength(2);
  expect(generated.map.entries[0].exampleId).toBe("ex:test.md:1");
  expect(generated.map.entries[1].exampleId).toBe("ex:test.md:2");

  for (const entry of generated.map.entries) {
    const genLines = getBodyLines(
      generated.code,
      entry.genCodeStartLine,
      entry.genCodeEndLine,
    );
    expect(genLines.length).toBeGreaterThan(0);
  }
});

test("nested doc path generates nested test file path", () => {
  const doc: Document = {
    id: "doc:docs/guide.md",
    file: "docs/guide.md",
    origin: "markdown",
    exampleIds: ["ex:docs/guide.md:abc123"],
  };

  const ex: Example = {
    id: "ex:docs/guide.md:abc123",
    documentId: "doc:docs/guide.md",
    source: {
      file: "docs/guide.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 6, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "docs/guide.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 7, column: 1, offset: 110 },
    },
    language: "ts",
    code: "expect(1).toBe(1);",
    kind: "assertion",
    title: "Test",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  expect(generated.path).toBe("docs/guide.md.test.ts");
  expect(generated.map.source).toBe("docs/guide.md");
  expect(generated.map.testFile).toBe("docs/guide.md.test.ts");
});

test("generated file contains valid test syntax and passes basic checks", async () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:abc123"],
  };

  const ex: Example = {
    id: "ex:test.md:abc123",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 2, column: 1, offset: 50 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 2, column: 1, offset: 50 },
    },
    language: "ts",
    code: "expect(1 + 1).toBe(2);",
    kind: "assertion",
    title: "Math test",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  expect(generated.code).toContain(
    'import { describe, test, expect } from "bun:test";',
  );
  expect(generated.code).toContain('describe("test.md", () => {');
  expect(generated.code).toContain(
    'test("Math test (test.md:1)", async () => {',
  );
  expect(generated.code).toContain("expect(1 + 1).toBe(2);");
  expect(generated.code).toContain("});");

  const transpiler = new Bun.Transpiler({ loader: "ts" });
  const transpiledCode = transpiler.transformSync(generated.code);
  expect(transpiledCode).toBeDefined();
});

test("multiple documents are sorted by file path", () => {
  const docs: Document[] = [
    {
      id: "doc:z.md",
      file: "z.md",
      origin: "markdown",
      exampleIds: ["ex:z.md:1"],
    },
    {
      id: "doc:a.md",
      file: "a.md",
      origin: "markdown",
      exampleIds: ["ex:a.md:1"],
    },
    {
      id: "doc:m.md",
      file: "m.md",
      origin: "markdown",
      exampleIds: ["ex:m.md:1"],
    },
  ];

  const examples: Example[] = [
    {
      id: "ex:z.md:1",
      documentId: "doc:z.md",
      source: {
        file: "z.md",
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: 10 },
      },
      fenceSource: {
        file: "z.md",
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: 10 },
      },
      language: "ts",
      code: "// z",
      kind: "assertion",
      title: "Z test",
    },
    {
      id: "ex:a.md:1",
      documentId: "doc:a.md",
      source: {
        file: "a.md",
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: 10 },
      },
      fenceSource: {
        file: "a.md",
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: 10 },
      },
      language: "ts",
      code: "// a",
      kind: "assertion",
      title: "A test",
    },
    {
      id: "ex:m.md:1",
      documentId: "doc:m.md",
      source: {
        file: "m.md",
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: 10 },
      },
      fenceSource: {
        file: "m.md",
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 2, column: 1, offset: 10 },
      },
      language: "ts",
      code: "// m",
      kind: "assertion",
      title: "M test",
    },
  ];

  const docSet = createDocSet(docs, examples);
  const generated = generate(docSet);

  expect(generated).toHaveLength(3);
  expect(generated[0].path).toBe("a.md.test.ts");
  expect(generated[1].path).toBe("m.md.test.ts");
  expect(generated[2].path).toBe("z.md.test.ts");
});

test("examples within document are sorted by source offset", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:2", "ex:test.md:1", "ex:test.md:3"],
  };

  const examples: Example[] = [
    {
      id: "ex:test.md:2",
      documentId: "doc:test.md",
      source: {
        file: "test.md",
        start: { line: 10, column: 1, offset: 100 },
        end: { line: 11, column: 1, offset: 150 },
      },
      fenceSource: {
        file: "test.md",
        start: { line: 9, column: 1, offset: 90 },
        end: { line: 12, column: 1, offset: 160 },
      },
      language: "ts",
      code: "// second",
      kind: "assertion",
      title: "Second",
    },
    {
      id: "ex:test.md:1",
      documentId: "doc:test.md",
      source: {
        file: "test.md",
        start: { line: 5, column: 1, offset: 50 },
        end: { line: 6, column: 1, offset: 100 },
      },
      fenceSource: {
        file: "test.md",
        start: { line: 4, column: 1, offset: 40 },
        end: { line: 7, column: 1, offset: 110 },
      },
      language: "ts",
      code: "// first",
      kind: "assertion",
      title: "First",
    },
    {
      id: "ex:test.md:3",
      documentId: "doc:test.md",
      source: {
        file: "test.md",
        start: { line: 15, column: 1, offset: 200 },
        end: { line: 16, column: 1, offset: 250 },
      },
      fenceSource: {
        file: "test.md",
        start: { line: 14, column: 1, offset: 190 },
        end: { line: 17, column: 1, offset: 260 },
      },
      language: "ts",
      code: "// third",
      kind: "assertion",
      title: "Third",
    },
  ];

  const docSet = createDocSet([doc], examples);
  const [generated] = generate(docSet);

  const code = generated.code;
  const firstIdx = code.indexOf("// first");
  const secondIdx = code.indexOf("// second");
  const thirdIdx = code.indexOf("// third");

  expect(firstIdx).toBeLessThan(secondIdx);
  expect(secondIdx).toBeLessThan(thirdIdx);
});

test("ignored examples are skipped entirely", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:normal", "ex:test.md:ignored"],
  };

  const normalEx: Example = {
    id: "ex:test.md:normal",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 6, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 7, column: 1, offset: 110 },
    },
    language: "ts",
    code: "expect(1).toBe(1);",
    kind: "assertion",
    title: "Normal test",
  };

  const ignoredEx: Example = {
    id: "ex:test.md:ignored",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 10, column: 1, offset: 150 },
      end: { line: 11, column: 1, offset: 200 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 9, column: 1, offset: 140 },
      end: { line: 12, column: 1, offset: 210 },
    },
    language: "ts",
    code: "pseudo_code();",
    kind: "ignored",
    title: "Ignored test",
  };

  const docSet = createDocSet([doc], [normalEx, ignoredEx]);
  const [generated] = generate(docSet);

  expect(generated.code).toContain("expect(1).toBe(1);");
  expect(generated.code).not.toContain("pseudo_code();");
  expect(generated.map.entries).toHaveLength(1);
  expect(generated.map.entries[0].exampleId).toBe("ex:test.md:normal");
});

test("document with only no-run examples still generates file", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:1"],
  };

  const ex: Example = {
    id: "ex:test.md:1",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 5, column: 1, offset: 50 },
      end: { line: 6, column: 1, offset: 100 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 4, column: 1, offset: 40 },
      end: { line: 7, column: 1, offset: 110 },
    },
    language: "ts",
    code: "const x = 1;",
    kind: "no-run",
    title: "No-run example",
  };

  const docSet = createDocSet([doc], [ex]);
  const generated = generate(docSet);

  expect(generated).toHaveLength(0);
});

test("empty document list produces empty output", () => {
  const docSet = createDocSet([], []);
  const generated = generate(docSet);
  expect(generated).toHaveLength(0);
});

test("imports with leading whitespace are preserved", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:1"],
  };

  const ex: Example = {
    id: "ex:test.md:1",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 3, column: 1, offset: 50 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 3, column: 1, offset: 50 },
    },
    language: "ts",
    code: '  import x from "m";\nexpect(x).toBeDefined();',
    kind: "assertion",
    title: "Indented import",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  const code = generated.code;
  expect(code).toContain('const { default: x } = await import("m");');
});

test("import with both default and named specifiers", () => {
  const doc: Document = {
    id: "doc:test.md",
    file: "test.md",
    origin: "markdown",
    exampleIds: ["ex:test.md:1"],
  };

  const ex: Example = {
    id: "ex:test.md:1",
    documentId: "doc:test.md",
    source: {
      file: "test.md",
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 2, column: 1, offset: 50 },
    },
    fenceSource: {
      file: "test.md",
      start: { line: 1, column: 1, offset: 0 },
      end: { line: 2, column: 1, offset: 50 },
    },
    language: "ts",
    code: 'import React, { useState } from "react"',
    kind: "assertion",
    title: "Mixed import",
  };

  const docSet = createDocSet([doc], [ex]);
  const [generated] = generate(docSet);

  const code = generated.code;
  expect(code).toContain('await import("react")');
  expect(code).toContain("const");
});
