/**
 * Renders metonym's own public API (the src/index.ts surface) into
 * docs/api.md + docs/api.json via `metonym extract --format=json` — the
 * reference-renderer pattern from examples/extract-docs-site, pointed at
 * this repo. Also runs every other built-in format (build's json/jsonl/
 * markdown/html, graph, coverage) into docs/build/ (gitignored).
 */

import { posix } from "node:path";
import { $ } from "bun";
import type {
  DocumentationSet,
  Example,
  HoverInfo,
  SymbolInfo,
} from "../src/ir/types";

const root = posix.join(import.meta.dir, "..");
const cli = posix.join(root, "src/cli/main.ts");
const INDEX_FILE = "src/index.ts";

const timings: { label: string; ms: number }[] = [];

async function timed<T>(label: string, fn: () => Promise<T>): Promise<T> {
  const start = performance.now();
  const result = await fn();
  timings.push({ label, ms: performance.now() - start });
  return result;
}

const ir = await timed(
  "extract --format=json",
  () =>
    $`bun ${cli} extract --format=json --full`
      .cwd(root)
      .json() as Promise<DocumentationSet>,
);

function resolveModule(fromFile: string, spec: string): string {
  const dir = posix.dirname(fromFile);
  const resolved = posix.normalize(posix.join(dir, spec));
  return resolved.endsWith(".ts") ? resolved : `${resolved}.ts`;
}

interface PublicEntry {
  name: string;
  file: string;
  symbol?: SymbolInfo;
}

const byFileAndName = new Map<string, SymbolInfo>();
for (const s of ir.symbols) byFileAndName.set(`${s.file}::${s.name}`, s);

const entries: PublicEntry[] = [];
const seen = new Set<string>();

for (const s of ir.symbols) {
  if (s.file !== INDEX_FILE || s.declKind !== "reexport" || !s.reexportFrom) {
    continue;
  }
  const targetFile = resolveModule(INDEX_FILE, s.reexportFrom);

  if (s.name === "*") {
    // `export * from "./x"` isn't enumerated by name at this level — every
    // non-reexport symbol declared in the target file is part of the surface.
    for (const t of ir.symbols) {
      if (t.file !== targetFile || t.declKind === "reexport") continue;
      const key = `${t.file}::${t.name}`;
      if (seen.has(key)) continue;
      seen.add(key);
      entries.push({ name: t.name, file: t.file, symbol: t });
    }
    continue;
  }

  const key = `${targetFile}::${s.name}`;
  if (seen.has(key)) continue;
  seen.add(key);
  entries.push({
    name: s.name,
    file: targetFile,
    symbol: byFileAndName.get(key),
  });
}

entries.sort(
  (a, b) => a.file.localeCompare(b.file) || a.name.localeCompare(b.name),
);

// ── docs/api.md — human reference ────────────────────────────────────────

const byFile = new Map<string, PublicEntry[]>();
for (const e of entries) {
  const list = byFile.get(e.file) ?? [];
  list.push(e);
  byFile.set(e.file, list);
}

const lines: string[] = [
  "<!-- generated by scripts/build-api-docs.ts — do not edit by hand -->",
  "# API reference",
  "",
  `Extracted from ${entries.length} exports reachable from \`${INDEX_FILE}\`, via ` +
    "`metonym extract --format=json` run against this repo's own `src/`. " +
    "See also [api.json](api.json) (machine-readable) and " +
    "[build/](build/) (every other built-in render format, dogfooded the " +
    "same way).",
  "",
];

for (const [file, fileEntries] of byFile) {
  lines.push(`## ${file}`, "");
  for (const e of fileEntries) {
    const sym = e.symbol;
    lines.push(`### \`${e.name}\``, "");
    if (!sym) {
      lines.push(
        `_Type-only export — not resolved by \`scanSymbols\` (see "Known limitations" below); see [source](../${e.file}) for its shape._`,
        "",
      );
      continue;
    }
    if (sym.loc) {
      lines.push(
        `[${sym.file}:${sym.loc.start.line}](../${sym.file}#L${sym.loc.start.line})`,
        "",
      );
    }
    if (sym.signature) lines.push(`\`${sym.signature}\``, "");
    if (sym.description) lines.push(sym.description, "");
    if (sym.tags) {
      for (const [tag, values] of Object.entries(sym.tags)) {
        for (const v of values) lines.push(`- \`@${tag}\` ${v}`);
      }
      lines.push("");
    }
    if (!sym.signature && !sym.description) {
      lines.push("_No signature or description resolved for this export._", "");
    }
  }
}

lines.push(
  "## Known limitations",
  "",
  "- Type-only exports (interfaces) show only their own name as a " +
    '"signature" — the checker doesn\'t expand a named object type by ' +
    "default, so follow the source link above for the actual shape.",
  "- `build`'s renderer output paths are root-relative, not `--out-dir`-" +
    "relative: rendering `docs/api.md` itself (it matches the default " +
    "`docs/**/*.md` include glob) into `--out-dir=docs/build` lands at " +
    "`docs/build/docs/api.md`, not `docs/build/api.md`.",
  "",
);

await timed("render docs/api.md", () =>
  Bun.write(posix.join(root, "docs/api.md"), `${lines.join("\n")}\n`),
);

// ── docs/api.json — machine reference ────────────────────────────────────

const apiJson = {
  generatedBy: "scripts/build-api-docs.ts",
  indexFile: INDEX_FILE,
  irVersion: ir.irVersion,
  toolVersion: ir.tool.version,
  exports: entries.map((e) => ({
    name: e.name,
    file: e.file,
    line: e.symbol?.loc?.start.line ?? null,
    declKind: e.symbol?.declKind ?? null,
    signature: e.symbol?.signature ?? null,
    description: e.symbol?.description ?? null,
    tags: e.symbol?.tags ?? null,
    typeOnly: e.symbol === undefined,
  })),
};

await timed("render docs/api.json", () =>
  Bun.write(
    posix.join(root, "docs/api.json"),
    `${JSON.stringify(apiJson, null, 2)}\n`,
  ),
);

// ── docs/build/ — every other built-in format ─────────────────────────────
//
// No --full below: the extract-cache/deep-analysis-cache are content-hash
// keyed, so reusing what the initial extract just populated is safe, and
// far cheaper than redoing TypeScript's ~1s cold start per command.

const buildDir = posix.join(root, "docs/build");
await $`rm -rf ${buildDir}`;

for (const format of ["json", "jsonl", "markdown", "html"]) {
  await timed(`build --format=${format}`, () =>
    $`bun ${cli} build --format=${format} --run --out-dir=docs/build`.cwd(root),
  );
}
await timed("graph --format=json", () =>
  $`bun ${cli} graph --format=json > docs/build/graph.json`.cwd(root),
);
await timed("graph --format=mermaid", () =>
  $`bun ${cli} graph --format=mermaid > docs/build/graph.mermaid`.cwd(root),
);
await timed("coverage --reporter=json", () =>
  $`bun ${cli} coverage --reporter=json > docs/build/coverage.json`.cwd(root),
);

// ── docs/build/hovers.html — Twoslash-style annotated examples ───────────
//
// metonym ships no renderer for `example.hovers` (deep-analysis-only,
// per-identifier `{ start, length, info, docs?, symbol? }`, same shape as
// Twoslash's `^?` queries — see README's "Docs as data"). Tooltips use
// `data-tip` + CSS `::after` rather than the native `title` attribute,
// which is slow to appear and unreliable over `<pre>/<code>`. Spans are
// `tabindex="0"` with the tooltip on `:focus-visible` too, so keyboard
// tabbing surfaces the same info a mouse hover would.

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Render one example's code with each hover span wrapped in a tooltip. */
function renderHoverCode(example: Example): string {
  const code = example.code;
  const hovers: HoverInfo[] = (example.hovers ?? [])
    .slice()
    .sort((a, b) => a.start - b.start);

  let out = "";
  let pos = 0;
  for (const h of hovers) {
    if (h.start < pos) continue; // overlapping span — keep the first
    out += escapeHtml(code.slice(pos, h.start));
    const span = code.slice(h.start, h.start + h.length);
    const tooltip = [h.info, h.docs].filter(Boolean).join("\n\n");
    out += `<span class="hover" tabindex="0" data-tip="${escapeHtml(tooltip)}">${escapeHtml(span)}</span>`;
    pos = h.start + h.length;
  }
  out += escapeHtml(code.slice(pos));
  return out;
}

function renderHoversPage(docs: DocumentationSet): string {
  const withHovers = docs.examples.filter((e) => (e.hovers?.length ?? 0) > 0);
  const sections = docs.examples
    .map((e) => {
      const hoverCount = e.hovers?.length ?? 0;
      return `<section>
<h2>${escapeHtml(e.title)}</h2>
<p class="meta">${hoverCount} hover${hoverCount === 1 ? "" : "s"} · ${escapeHtml(e.source.file)}:${e.source.start.line}</p>
<pre><code>${renderHoverCode(e)}</code></pre>
</section>`;
    })
    .join("\n");

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>metonym — hover reference</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }
  pre { background: #f6f8fa; padding: 24px 16px 16px; border-radius: 6px; overflow: visible; }
  code { font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 13px; white-space: pre; }
  .hover { border-bottom: 2px dotted #0969da; cursor: help; position: relative; }
  .hover:hover, .hover:focus-visible { background: #ddf4ff; outline: none; }
  .hover:hover::after, .hover:focus-visible::after {
    content: attr(data-tip);
    position: absolute;
    left: 0;
    bottom: 100%;
    margin-bottom: 6px;
    background: #24292f;
    color: #fff;
    padding: 8px 10px;
    border-radius: 6px;
    font-size: 12px;
    line-height: 1.5;
    white-space: pre-wrap;
    width: max-content;
    max-width: 420px;
    z-index: 10;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.25);
  }
  .meta { color: #666; font-size: 13px; }
</style>
</head>
<body>
<h1>metonym — hover reference</h1>
<p>Twoslash-style rendering of <code>example.hovers</code> (deep-analysis IR data metonym itself doesn't render). ${withHovers.length}/${docs.examples.length} examples have hover data. Hover any underlined token.</p>
${sections}
</body>
</html>
`;
}

await timed("render docs/build/hovers.html", () =>
  Bun.write(posix.join(root, "docs/build/hovers.html"), renderHoversPage(ir)),
);

process.stdout.write(
  `docs/api.md, docs/api.json (${entries.length} exports), docs/build/* (json, jsonl, markdown, html, hovers.html, graph, coverage)\n\n`,
);

const labelWidth = Math.max(...timings.map((t) => t.label.length));
let total = 0;
for (const { label, ms } of timings) {
  total += ms;
  process.stdout.write(`  ${label.padEnd(labelWidth)}  ${ms.toFixed(0)}ms\n`);
}
process.stdout.write(
  `  ${"total".padEnd(labelWidth)}  ${total.toFixed(0)}ms\n`,
);
